name: "Freelance Computing Support"
description: "Freelance Computing Support. For all your home computing and software support needs, look no further."
logo: "/images/logo.png"
url: "http://freelance-computing-support.com" 
baseurl: ""
github: [metadata]
markdown: kramdown
port: 4003
input: GFM
hard_wrap: false
gems:
   - jekyll-coffeescript
   - jekyll-paginate
